files:
  - source: /en/*.md
    translation: /%two_letters_code%/%original_file_name%
  - source: /en/*.json
    translation: /%two_letters_code%/%original_file_name%
  - source: /en/home.json
    translation: /%two_letters_code%/home.json
